name: Context Printer
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: github
        run: echo "${{ toJSON(github) }}"
      - name: env
        run: echo "${{ toJSON(env) }}"
      - name: vars
        run: echo "${{ toJSON(vars) }}"
      - name: job
        run: echo "${{ toJSON(job) }}"
      - name: jobs
        run: echo "${{ toJSON(jobs) }}"
                
                
        
