# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --ignore-scripts
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Run Playwright tests
        run: npx playwright test
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Create unique folder
        run: mkdir playwright-report-${{ github.event.pull_request.number }}
      - name: Copy report files
        run: cp -R playwright-report/. playwright-report-${{ github.event.pull_request.number }}
      - name: Deploy to S3 bucket
        uses: keithweaver/aws-s3-github-action@v1.0.0
        id: deployment
        with:
          command: cp
          source: ./playwright-report-${{ github.event.pull_request.number }}/index.html
          destination: s3://quizizz-cypress-test-results/dev/playwright-report-${{ github.event.pull_request.number }}/index.html
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
      - name: Set page URL output
        run: echo "::set-output name=page_url::https://quizizz-cypress-test-results.s3.amazonaws.com/dev/playwright-report-${{ github.event.pull_request.number }}/index.html"
      - name: Echo steps
        run: echo "${{toJson(steps)}}"
      - name: Echo page_url
        run: echo "${{steps.deployment.outputs.page_url}}"
  
  # Send notification on Slack
  notify:
    name: Notify on Slack
    runs-on: ubuntu-latest
    # Always run this job
    if: ${{ always() }}
    needs: [deploy]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Echo steps
        run: echo "${{toJson(steps)}}"
      - name: Echo needs
        run: echo "${{toJson(needs)}}"
      - name: Echo steps page_url
        run: echo "${{steps.deployment.outputs.page_url}}"
      - name: Echo needs page_url
        run: echo "${{needs.deploy.outputs.page_url}}"
      - uses: abinoda/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"commit ${{ github.sha }}\nAuthor: ${{github.event.commits[0].author.name}}\nDate: ${{steps.date.outputs.date}}\n\n\t\t${{github.event.head_commit.message}}\n\n\n\t\tTest report: ${{needs.deploy.outputs.page_url}}\"}}]}'

        # Pick up events even if the job is success.
        if: success()
